export const ORANGE_LINE_REVEAL_DURATION_MS = 500;
export const NAME_TYPING_START_EXTRA_DELAY_MS = 20;
export const HI_TYPING_INTERVAL_MS = 70;
export const ROLE_TYPING_INTERVAL_MS = 70;
export const ENGINEERING_TOOLKIT_TYPING_INTERVAL_MS = 45;
export const NAME_TYPING_INTERVAL_MS = 75;
export const NEED_MORE_DETAILS_TYPING_INTERVAL_MS = 45;
export const CV_DOWNLOAD_TYPING_INTERVAL_MS = 38;
export const HERO_TYPING_STEP_SINGLE_CHAR = 1;
export const HERO_TYPING_STEP_DOUBLE_CHARS = 2;

export const TIMELINE_REVEAL_STAGGER_MS = 240;
export const TIMELINE_REVEAL_DURATION_MS = 460;
export const TIMELINE_FOCUS_TRANSITION_MS = 460;

export const TAG_REVEAL_STAGGER_MS = 140;
export const TAG_REVEAL_DURATION_MS = 640;
